DEFINE
    MEASURE '1_MEDIDAS'[Importe_Total_Dinamico_2024_NoActivos2025] = VAR AbonadoActual = SELECTEDVALUE(dimAbonados[Nombre comercial open])
    VAR Envios2024 = CALCULATE(
        DISTINCTCOUNT('CARPETA DATOS CLIENTES'[Número envío]),
        FILTER(
            'CARPETA DATOS CLIENTES',
            YEAR('CARPETA DATOS CLIENTES'[Fecha envío]) = 2024
        )
    )
    VAR Envios2025 = CALCULATE(
        DISTINCTCOUNT('CARPETA DATOS CLIENTES'[Número envío]),
        FILTER(
            'CARPETA DATOS CLIENTES',
            YEAR('CARPETA DATOS CLIENTES'[Fecha envío]) = 2025
        )
    )
    VAR EsMasDeUnEnvio = Envios2024 > 1
    VAR Importe2024 = IFERROR(
        SUMX(
            SUMMARIZE(
                'CARPETA DATOS CLIENTES HISTÓRICO',
                'CARPETA DATOS CLIENTES HISTÓRICO'[Número envío],
                "TotalPorEnvio", VALUE(MAX('CARPETA DATOS CLIENTES HISTÓRICO'[Total]))
            ),
            [TotalPorEnvio]
        ),
        0
    )
    RETURN
        IF(
            EsMasDeUnEnvio && Envios2024 > 0 && Envios2025 = 0,
            Importe2024,
            BLANK()
        )

EVALUATE
    SUMMARIZECOLUMNS(
        "Importe_Total_Dinamico_2024_NoActivos2025", [Importe_Total_Dinamico_2024_NoActivos2025]
    )