table dimClasificacionAbonados
	lineageTag: ffd196f7-8ea0-48e2-9697-630322e27ffc

	column Orden
		dataType: int64
		formatString: 0
		lineageTag: 9897fec1-77ac-4c6c-b528-48836db96744
		summarizeBy: sum
		sourceColumn: Orden

		annotation SummarizationSetBy = Automatic

	column Clasificacion
		dataType: string
		lineageTag: f8e92086-bd68-4afd-a8b1-969e54fdbc10
		summarizeBy: none
		sourceColumn: Clasificacion
		sortByColumn: Orden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition dimClasificacionAbonados = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUfIrTS3LL1aK1YlWMgJyg1KTSwtSixJT8osVHPNKMtNLoZLGaJJAdmZqXkkqRNYEKOuWmZoD5ZoCuQGpRSmZIJWhOSUKxgq5qcVQSTN0SUMjmGwsAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Orden = _t, Clasificacion = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Orden", Int64.Type}, {"Clasificacion", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

