-- Consulta DAX para obtener TOP 10 Mensajeros - Última Semana
-- Entregas y Recogidas Finalizadas

EVALUATE
    TOPN(10,
        ADDCOLUMNS(
            SUMMARIZE(
                FILTER(
                    FacDatos1,
                    Fecha[AñoSemanaNum] = MAXX(ALL(Fecha[Año], Fecha[SemanaNum]), Fecha[AñoSemanaNum])
                ),
                'dimUsuario Mensajero'[Mensajero]
            ),
            "Entregas_Finalizadas", 
                SUMX(
                    FILTER(
                        FacDatos1,
                        Fecha[AñoSemanaNum] = MAXX(ALL(Fecha[Año], Fecha[SemanaNum]), Fecha[AñoSemanaNum])
                        && FacDatos1[Estadística] = " Entregas finalizadas"
                        && 'dimUsuario Mensajero'[Mensajero] = EARLIER('dimUsuario Mensajero'[Mensajero])
                    ),
                    FacDatos1[Valor]
                ),
            "Recogidas_Finalizadas",
                SUMX(
                    FILTER(
                        FacDatos1,
                        Fecha[AñoSemanaNum] = MAXX(ALL(Fecha[Año], Fecha[SemanaNum]), Fecha[AñoSemanaNum])
                        && FacDatos1[Estadística] = " Recogidas finalizadas"
                        && 'dimUsuario Mensajero'[Mensajero] = EARLIER('dimUsuario Mensajero'[Mensajero])
                    ),
                    FacDatos1[Valor]
                ),
            "Total_Operaciones",
                [Entregas_Finalizadas] + [Recogidas_Finalizadas]
        ),
        [Total_Operaciones],
        DESC
    )

ORDER BY [Total_Operaciones] DESC
